# Generated by Django 4.1.4 on 2022-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_file',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='file_field',
            field=models.FileField(upload_to='uploads/<django.db.models.fields.CharField>/'),
        ),
    ]
